config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: 'store#index', as: :store_root
  end

  root to: 'visitors#index'

  resources :ovens do
    resource :cookies
    member do
      post :empty
    end
  end

  resources :orders, only: [:index]

  namespace :api do
    resources :orders, only: [:index] do
      put :fulfill, on: :member
    end
  end

  mount MailPreview => 'mail_view' if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cookie.rb
class Cookie < ActiveRecord::Base
  belongs_to :storage, polymorphic: :true
  
  validates :storage, presence: true

  attr_accessor :how_many
end

app/models/order.rb
class Order < ApplicationRecord
  validates :customer_name, presence: true
  validates :item, presence: true
  validates :pick_up_at, presence: true
end

app/models/oven.rb
class Oven < ActiveRecord::Base
  STATUS_COOKING = 'Cooking'.freeze
  STATUS_DONE = 'Done'.freeze

  belongs_to :user
  has_many :cookies, as: :storage, dependent: :destroy

  validates :user, presence: true
  validates_inclusion_of :status, :in => [STATUS_COOKING, STATUS_DONE], allow_nil: true

  def finished_cooking?
    reload.status == STATUS_DONE
  end

  # TODO: If i had more time, i would abstract this out into a Cooking class.  This would
  # also allow the Sidekiq job to be better abstracted for testing simulation and mocking
  # Having this here for now seems fine, but this pattern can quickly lead to model bloat and non-SRP
  def bake_some_cookies(count, cookie_params)
    count.times { cookies.create!(cookie_params) }

    CookingJob.perform_async(id)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :ovens, dependent: :destroy
  has_many :stored_cookies, class_name: 'Cookie', as: :storage

  before_create :setup_first_oven

  private

  def setup_first_oven
    ovens.new(name: 'My First Oven')
  end
end

app/controllers/api/base_controller.rb
class Api::BaseController < ActionController::API
end

app/controllers/api/orders_controller.rb
class Api::OrdersController < Api::BaseController
  def index
    sleep 30 unless Rails.env.test? # simulate delay in loading
    @orders = Order.all.order(created_at: :desc)
  end

  def fulfill
    @order = Order.find(params[:id])
    @order.fulfilled = true
    @order.save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :basic_authenticate

  private def basic_authenticate
    return if Rails.env.test?

    authenticate_or_request_with_http_basic do |username, password|
      username == 'bake' && password == 'somecookies'
    end
  end
end

app/controllers/cookies_controller.rb
class CookiesController < ApplicationController
  before_action :authenticate_user!

  def new
    @oven = current_user.ovens.find_by!(id: params[:oven_id])
    if @oven.cookies.empty?
      @cookie = @oven.cookies.build
    else
      redirect_to @oven, alert: 'A cookie or more is already in the oven!'
    end
  end

  def create
    @oven = current_user.ovens.find_by!(id: params[:oven_id])
    how_many = params[:cookie][:how_many].to_i

    @oven.bake_some_cookies(how_many, cookie_params)

    redirect_to oven_path(@oven)
  end

  private

  def cookie_params
    params.require(:cookie).permit(:fillings)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  end
end

app/controllers/ovens_controller.rb
class OvensController < ApplicationController
  before_action :authenticate_user!

  def index
    @ovens = current_user.ovens
  end

  def show
    @oven = current_user.ovens.find_by!(id: params[:id])
  end

  def empty
    @oven = current_user.ovens.find_by!(id: params[:id])
    if @oven.cookies
      @oven.cookies.each { |cookie| cookie.update_attributes!(storage: current_user) }
    end
    redirect_to @oven, alert: 'Oven emptied!'
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cookies/new.html.haml
%h3 New Cookie(s) for oven '#{@oven.name}'

= form_for [@oven, @cookie] do |f|
  .row
    .small-8.columns
      = f.label :fillings
  .row
    .small-8.columns
      = f.text_field :fillings
  .row
    .small-8.columns
      = f.label 'How many (1 - 10)'
  .row
    .small-8.columns
      = f.number_field :how_many, min: 1, max: 10
  - 2.times do
    %br
  .row
    .small-8.columns
      = f.submit 'Mix and bake', class: 'button'

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 4.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role  => "alert"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-expand-md.navbar-dark.bg-dark
  = link_to "Classroom Bakery", root_path, class: 'navbar-brand'
  %button.navbar-toggler{"aria-controls" => "navbarNav", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNav", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarNav.collapse.navbar-collapse
    %ul.nav.navbar-nav= render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
- if user_signed_in?
  %li.nav-item
    = link_to 'Edit account', edit_user_registration_path, class: 'nav-link'
  %li.nav-item
    = link_to 'Sign out', destroy_user_session_path, method: 'delete', class: 'nav-link'
  %li.nav-item
    = link_to 'Order listing', orders_path, class: 'nav-link'
- else
  %li.nav-item
    = link_to 'Sign in', new_user_session_path, class: 'nav-link'
  %li.nav-item
    = link_to 'Sign up', new_user_registration_path, class: 'nav-link'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Classroom Bakery'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Classroom Bakery2'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    = javascript_pack_tag 'orders'
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/orders/index.html.haml
%h2 Orders

%br

%div{data:{'order-table': true}}

app/views/ovens/index.html.haml
%h3 My Ovens

%ul.ovens
  - @ovens.each do |oven|
    %li= link_to oven.name, oven

app/views/ovens/show.html.haml
%h3= @oven.name

.cookie-info
  Cookie(s) in oven:
  - if @oven.cookies.present?
    - @oven.cookies.each do |cookie|
      %li= "A cookie with #{cookie.fillings || "no fillings"}"
    - 2.times do
      %br
    - ready_class = (@oven.finished_cooking?) ? "" : "hidden"
    %div{ :id => "ready_#{@oven.id}", :class => ready_class }
      - if @oven.cookies.count > 1
        (Your Cookies are Ready)
      - else
        (Your Cookie is Ready)
      = button_to "Retrieve Cookie(s)", empty_oven_path, class: 'button tiny'

    %br
    - unless @oven.finished_cooking?
      %div{ :id => "take_em_out_#{@oven.id}" }
        = button_to "Take 'em out anyway", empty_oven_path, class: 'button tiny'

  - else
    None

%br

= link_to "Prepare Cookie", new_oven_cookies_path(@oven), class: 'button'

app/views/pages/about.html.haml
- content_for :title do
  About
%h3 About the Website
%p
  This web application was created with
  = link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/')
  from the #{link_to('RailsApps project', 'http://railsapps.github.io/')}.

app/views/store/index.html.haml
%h3 Your Bakery

.bakery-nav
  = link_to "View your ovens", ovens_path

%br

.store-inventory
  Cookies for sale:
  %ul
    - current_user.stored_cookies.group_by(&:fillings).each_pair do |fillings, cookies|
      %li
        = pluralize(cookies.count, "Cookie")
        with
        = fillings || "no filling"
    

app/views/visitors/index.html.haml
%h3 Welcome to the Classroom Bakery